version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # Note: No group defined here
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
